### PR TITLE
Fix setup.py to use new markdown readme & changelog files

### PR DESCRIPTION
**Pull request by othalla**

### CODE REVIEW

**Comment by othalla** [comment]
Why do we wait before merging it?

**Comment by alexjfisher** [comment]
@othalla Thanks!

> Why do we wait before merging it?

Sometimes I wait to see if anyone else is going to have an opinion.  I didn't mean to wait 4 weeks though! :)  Thanks for bugging me.

**Comment by othalla** [comment]
@alexjfisher ok no problem
Any info regarding some new release?

**Comment by alexjfisher** [comment]
@othalla It's been a while, hasn't it?  I'll see if I can get this progressed.  Ideally we'd modify our travis setup so all git tags are automatically deployed to PyPi.

@mterzo @corey-hammerton Would one of you be able to add the Vox Pupuli PyPi account I've just created as a maintainer of https://pypi.org/project/puppetboard/ and https://pypi.org/project/pypuppetdb/ The account username is `voxpupuliorg`.  Thanks.

**Comment by othalla** [comment]
@alexjfisher it would be nice :)
let me know if you need some help!

**Comment by bastelfreak** [comment]
@othalla are you able to review some of the existing PRs? Python knowledge is a bit rare in our community.

**Comment by othalla** [comment]
Yes i'm able to review some.
I'm just more a backend/infrastructure. I'm not friendly with frontend and there is some in puppetboard.
i'll do what i can

**Pull request merged**
