### PR TITLE
Fix #383

### LINKED ISSUE #383: Internal Server Error when viewing reports
Everything on my install works great, except if go to "Reports" or load up a Node (its list of reports never populates - everything else shows fine).

Where the data table of Reports should be it just says Processing... and then in the console there's a 500. Tracing that into the logs I see this:

```
ERROR:pypuppetdb.api:Illegal value '{:field "end_time", :order "None"}' in :order_by; 'order' must be either 'asc' or 'desc' puppetdb.dev.local:8080 over HTTP.
```

Here is `settings.py`

```
DEV_LISTEN_HOST = '127.0.0.1'
DEV_LISTEN_PORT = 5000
LOGLEVEL = 'info'
PUPPETDB_HOST = 'puppetdb.dev.local'
PUPPETDB_PORT = 8080
PUPPETDB_SSL_VERIFY = False
PUPPETDB_TIMEOUT = 20
UNRESPONSIVE_HOURS = 3
ENABLE_CATALOG = False
ENABLE_QUERY = True
LOCALISE_TIMESTAMP = True
OFFLINE_MODE = False
PUPPETDB_EXPERIMENTAL = False
DEFAULT_ENVIRONMENT = 'dev'
REPORTS_COUNT = 10
```

I'm sure its something I'm doing wrong, but what could be going on here? I'm on PuppetDB 4.3.2

### PR DESCRIPTION
**Pull request by redref**
#383 

I can not reproduce on my side but this should avoid the error. I guess the error come from JS.

Please test it and get back to me (default order as well).

### CODE REVIEW

**Comment by mterzo** [comment]
Why is it missing?

**Comment by redref** [comment]
I guess it is browser related. Default is supplied in datatables configuration.

Catalogs part is already covered with this trick.

We need input from @phybros

**Comment by mterzo** [comment]
That's so strange, so in that browser will it ever be able to specify order.

**Comment by phybros** [comment]
@redref I just tried this in my environment and it seems to have almost worked. Now dataTables complains that the response is invalid JSON, which it is.

Here's the error

screen shot 2017-06-06 at 13 21 27

And here's the first part of the response:

```
<html><body><p>{
  &quot;draw&quot;: 2,
  &quot;recordsTotal&quot;: 92244,
  &quot;recordsFiltered&quot;: 92244,
  &quot;data&quot;: [[&quot;<span rel="\&quot;utctimestamp\&quot;">2017-06-06 17:18:51.585000+00:00</span>&quot;,&quot;<a class="\&quot;ui" unchanged label status href="\&quot;/report/mongo1-7.staging.local/72c3a622cf8629dd58091de3dbcd36b5c0f82956\&quot;">UNCHANGED</a>\n  \n    <span class="\&quot;ui" small count label>0</span>\n    <span class="\&quot;ui" small count label>0</span>\n    <span class="\&quot;ui" small count label>0</span>\n  &quot;,&quot;<a href="\&quot;/node/mongo1-7.trello.local/\&quot;">mongo1-7.trello.local</a>&quot;,&quot;1496769530&quot;,&quot;3.8.4&quot;]

... the rest of the reports follow here
```

Something wrong with datatables? I'm just using the latest Chrome on Mac, nothing crazy

**Comment by mterzo** [comment]
Any odd extensions?

Running Chrome on mac: Version 59.0.3071.86 (Official Build) (64-bit)

**Comment by phybros** [comment]
No, I had ublock, but this domain is whitelisted. I disabled all the rest and still get the same result. What do you get for the /reports/json endpoint when you load that page? Is it JSON?

**Comment by mterzo** [comment]
In theory, try this and replace your host.

```
curl -v "http://puppetboard.internal.terzo.org/reports/json?draw=2&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&colmns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=*&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=desc&start=0&length=100&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1496771861129"

results:
> Host: puppetboard.internal.terzo.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: gunicorn/19.6.0
< Date: Tue, 06 Jun 2017 17:58:02 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 47943
< 
{
  "draw": 2,
  "recordsTotal": 1842,
  "recordsFiltered": 1842,
  "data": [["<span rel=\"utctimestamp\">2017-06-06 17:28:55.928000+00:00</span>","<a class=\"ui unchanged label status\" href=\"/report/docker01.internal.terzo.org/6a58ac2591dfdaa3b8c42848862be658f803440f\">UNCHANGED</a>\n  \n    <span class=\"ui small count label\">0</span>\n    <span class=\"ui small count label\">0</span>\n    <span class=\"ui small count label\">0</span>\n  ","<a href=\"/node/docker01.internal.terzo.org/\">docker01.internal.terzo.org</a>","1496770174","4.10.1"]
....

```

This is the default query that gets created on that page.




I wonder, if your nginx/apache configuration is limiting query length.

**Comment by phybros** [comment]
AHA: we were running it behind an Apache2 reverse proxy, and the config for Apache had this in it:

```
SetOutputFilter INFLATE;proxy-html;DEFLATE;
```

Which I assume is what was wrapping the JSON in those HTML tags and HTML encoding it. Removing that directive seems to have solved the issue - but only if I leave the change in this PR in place. Let me try some different configs with Apache and see if I can solve this that way.

**Comment by mterzo** [comment]
YAY! We are cooking with gas now!

**Comment by mterzo** [comment]
Make sure this isn't really low: http://httpd.apache.org/docs/2.0/mod/core.html#limitrequestline

Our URL requests get long.
```
$ wc -c foo 
    1188 foo
```

**Comment by phybros** [comment]
Is there a way to tell puppetboard that its hrefs should be at a different base URL? i.e. `/puppetboard` instead of `/`?

**Comment by phybros** [comment]
ah

```
APPLICATION_ROOT = '/puppetboard'
```

**Comment by phybros** [comment]
uhhhh, nvm, that doesn't seem to have helped...

**Comment by mterzo** [comment]
I don't see how the app root was related to the issue.

Your apache should be logging the GET requests, can you post the line for the /reports/json

**Comment by redref** [comment]
Issue seems to be solved ! Good :) Merge ?

In order to get "APPLICATION_ROOT" to work (I mean without mod_proxy_html), you may need to change WSGI mount point / alias on your backend server. I don't see any other option.

**Comment by mterzo** [comment]
It's fixed the key error, but the I don't think the UI is going to be functional if for some reason the GET params are getting truncated.

**Comment by redref** [comment]
We can switch datatables to POST.

Should we make it a default behavior ?

**Comment by phybros** [comment]
So, I changed the `APPLICATION_ROOT` TO `/puppetboard` and also changed my `wsgi.py` to reflect that.

The main "Reports" page now loads fine. If I try and sort it, I get an error like this in the log:

```
[Tue Jun 06 15:39:10.740995 2017] [:error] [pid 21902] ERROR:puppetboard.app:Exception on /reports/json [GET]
[Tue Jun 06 15:39:10.741014 2017] [:error] [pid 21902] Traceback (most recent call last):
[Tue Jun 06 15:39:10.741017 2017] [:error] [pid 21902]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Tue Jun 06 15:39:10.741019 2017] [:error] [pid 21902]     response = self.full_dispatch_request()
[Tue Jun 06 15:39:10.741029 2017] [:error] [pid 21902]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Tue Jun 06 15:39:10.741031 2017] [:error] [pid 21902]     rv = self.handle_user_exception(e)
[Tue Jun 06 15:39:10.741033 2017] [:error] [pid 21902]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Tue Jun 06 15:39:10.741034 2017] [:error] [pid 21902]     reraise(exc_type, exc_value, tb)
[Tue Jun 06 15:39:10.741036 2017] [:error] [pid 21902]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Tue Jun 06 15:39:10.741037 2017] [:error] [pid 21902]     rv = self.dispatch_request()
[Tue Jun 06 15:39:10.741039 2017] [:error] [pid 21902]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Tue Jun 06 15:39:10.741040 2017] [:error] [pid 21902]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Jun 06 15:39:10.741042 2017] [:error] [pid 21902]   File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 555, in reports_ajax
[Tue Jun 06 15:39:10.741043 2017] [:error] [pid 21902]     for metrics in report.metrics:
[Tue Jun 06 15:39:10.741045 2017] [:error] [pid 21902] TypeError: 'NoneType' object is not iterable
```

The same thing if I go to an individual Node page, and the little table of reports tries to load. I've made sure that my GET params are not being truncated by increasing the request line limit to `8190` (which I think is the default for apache anyway).

**Comment by mterzo** [comment]
Any chance you have SELinux enabled?

I know that SELinux didn't like the HTTP forward stuff: https://serverfault.com/questions/329355/issues-with-proxypass-and-proxypassreverse-when-proxying-to-localhost-and-a-diff

I'm wondering if it's dong something off.

Also you can turn up puppetboard logging: 

```
settings.py
LOGLEVEL = 'debug'
```

**Comment by phybros** [comment]
No SELinux, but I'll poke around with debug on

**Comment by phybros** [comment]
So with debug logging on, if I load up the Reports page (loads fine) and then click the column header for Certname for example, this happens:

```
[Tue Jun 06 17:01:00.808774 2017] [:error] [pid 7335] DEBUG:pypuppetdb.api:_query called with endpoint: environments, path: None, query: None, limit: None, offset: None, summarize_by None, count_by None, count_filter: None
[Tue Jun 06 17:01:00.808962 2017] [:error] [pid 7335] DEBUG:pypuppetdb.api:_url called with endpoint: environments and path: None
[Tue Jun 06 17:01:00.813735 2017] [:error] [pid 7335] DEBUG:requests.packages.urllib3.connectionpool:"GET /pdb/query/v4/environments HTTP/1.1" 200 16
[Tue Jun 06 17:01:00.814218 2017] [:error] [pid 7335] DEBUG:pypuppetdb.api:_query called with endpoint: reports, path: None, query: ["and",["=", "environment", "dev"]], limit: 100, offset: 0, summarize_by None, count_by None, count_filter: None
[Tue Jun 06 17:01:00.814340 2017] [:error] [pid 7335] DEBUG:pypuppetdb.api:_url called with endpoint: reports and path: None
[Tue Jun 06 17:01:00.837397 2017] [:error] [pid 7335] DEBUG:requests.packages.urllib3.connectionpool:"GET /pdb/query/v4/reports?query=%5B%22and%22%2C%5B%22%3D%22%2C+%22environment%22%2C+%22dev%22%5D%5D&order_by=%5B%7B%22field%22%3A+%22certname%22%2C+%22order%22%3A+%22desc%22%7D%5D&limit=100&include_total=true&offset=0 HTTP/1.1" 200 None
[Tue Jun 06 17:01:00.844149 2017] [:error] [pid 7335] ERROR:puppetboard.app:Exception on /reports/json [GET]
[Tue Jun 06 17:01:00.844205 2017] [:error] [pid 7335] Traceback (most recent call last):
[Tue Jun 06 17:01:00.844235 2017] [:error] [pid 7335]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Tue Jun 06 17:01:00.844265 2017] [:error] [pid 7335]     response = self.full_dispatch_request()
[Tue Jun 06 17:01:00.844291 2017] [:error] [pid 7335]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Tue Jun 06 17:01:00.844315 2017] [:error] [pid 7335]     rv = self.handle_user_exception(e)
[Tue Jun 06 17:01:00.844337 2017] [:error] [pid 7335]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Tue Jun 06 17:01:00.844359 2017] [:error] [pid 7335]     reraise(exc_type, exc_value, tb)
[Tue Jun 06 17:01:00.844385 2017] [:error] [pid 7335]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Tue Jun 06 17:01:00.844414 2017] [:error] [pid 7335]     rv = self.dispatch_request()
[Tue Jun 06 17:01:00.844435 2017] [:error] [pid 7335]   File "/srv/puppetboard/virtenv-puppetboard/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Tue Jun 06 17:01:00.844458 2017] [:error] [pid 7335]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Jun 06 17:01:00.844480 2017] [:error] [pid 7335]   File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 555, in reports_ajax
[Tue Jun 06 17:01:00.844503 2017] [:error] [pid 7335]     for metrics in report.metrics:
[Tue Jun 06 17:01:00.844525 2017] [:error] [pid 7335] TypeError: 'NoneType' object is not iterable
[Tue Jun 06 17:01:00.844628 2017] [:error] [pid 7335] DEBUG:pypuppetdb.api:_query called with endpoint: environments, path: None, query: None, limit: None, offset: None, summarize_by None, count_by None, count_filter: None
[Tue Jun 06 17:01:00.844724 2017] [:error] [pid 7335] DEBUG:pypuppetdb.api:_url called with endpoint: environments and path: None
[Tue Jun 06 17:01:00.848782 2017] [:error] [pid 7335] DEBUG:requests.packages.urllib3.connectionpool:"GET /pdb/query/v4/environments HTTP/1.1" 200 16
```

**Comment by mterzo** [comment]
Not much more help.

**Comment by phybros** [comment]
My issues were mostly created by my reverse proxy as it turned out, see my last comment on #383 for the solution

**Pull request merged**
