### PR TITLE
1.0.0 version and CHANGELOG

### PR DESCRIPTION
**Pull request by larsnaesbye**
This is a quick first attempt at a 1.0.0 changelog, based on the description of commits to master since the 0.3.0 release.

I skipped changes to documentation, typo fixes and similar "non-functional" things. Please do review and comment if something's missing.

### CODE REVIEW

**Comment by anarcat** [comment]
@daenney do you have merge access here? i think this is go. once we have that in, we just need to lay tag and push to pypi, we're almost there!

**Comment by daenney** [comment]
Unfortunately I don't anymore. @bastelfreak Would you mind temporarily re-adding me to tools/python so I can help get this release out? Currently both of the tools/python members appear to be otherwise occupied.

**Comment by daenney** [comment]
Ah, looks like he's on vacay. @voxpupuli/project-maintainers please?

**Comment by nibalizer** [comment]
For some reason I'm still able to do that (lol) and it is done. @daenney

**Comment by daenney** [comment]
@nibalizer Haha. Awesome. Thanks :heart:

**Comment by larsnaesbye** [comment]
@othalla - if you'd like to review Python code, there's been a request to review the PRs that passed CI. I've only looked at two of them.

**Comment by alexjfisher** [comment]
For the new release, I think it'd be best if we set up travis to build and deploy tags.  I can create a separate PR to add a suitable travis secret for the voxpupuli.org pypi account etc.  Might not get the time over the (long) weekend though.

@larsnaesbye Thanks for compiling the changelog.  Are you ok waiting a couple of days to get the travis bits setup?

**Comment by larsnaesbye** [comment]
@alexjfisher I sure am. Getting it right is worth waiting for :)

**Comment by bastelfreak** [comment]
Hi everybody. [Our account](https://pypi.org/user/voxpupuliorg/) is now registered as maintainer for the puppetboard and pypuppetdb projects. @mterzo already created a PR to automatically do [releases through travis](https://github.com/voxpupuli/pypuppetdb/pull/144). This needs to be rebased, reviewed and added to the puppetboard project as well. I will do the rebase on pypuppetdb and propose a PR here. It would be nice if one of you could review it. Afterwards we should be able to do a release for both projects.

**Comment by bastelfreak** [comment]
Hi again. I created https://github.com/voxpupuli/puppetboard/pull/503 to automate releases through travis. Whoever knows some python: please feel free to review.

**Comment by larsnaesbye** [comment]
#503 is merged, so... is this PR the last thing to do before the release?

**Comment by daenney** [comment]
Not quite, I have a few things I'd like to fix:

* [ ] Author in setup.py should be changed to Vox and the Vox mailinglists
* [ \ Fix tests on Python 3.7

**Comment by larsnaesbye** [comment]
Changed the author and email address to VP. Also edited the Python versions to match the one we support. It decreased coverage a tiny bit.

**Comment by daenney** [comment]
Yap, I see. Those calculations are always a bit wonky. Now we just need to get the tests passing. I don't want to release 1.0.0 in 2019 without Python 3.7 support sorted.

**Comment by larsnaesbye** [comment]
In that case, I'll add 3.7 to this too.

**Comment by othalla** [comment]
@larsnaesbye can you please rebase it?
Should we add CI enhancements to CHANGELOG?
Then we may be ready for the release !

**Comment by othalla** [comment]
Looks like better now, what do you think @bastelfreak @alexjfisher ?

**Comment by daenney** [comment]
Yap, seems good. Now all we need is a PR first to fix Python 3.7 tests and then we can merge this.

**Comment by othalla** [comment]
@daenney looks like it is done https://travis-ci.org/voxpupuli/puppetboard/builds/537735682

**Comment by bastelfreak** [comment]
In my opinion this is fine now. Do we have a dependency to the latest pypuppetdb pypi? So should we first release pypuppetdb and puppetdb 1.0.0 depends on latest pypuppetdb?

**Comment by daenney** [comment]
Sounds good. At this point we should bump pypuppetdb to 1.0, it's been long enough. And then have puppetboard 1.0 released depending on that one.

**Comment by othalla** [comment]
@daenney agreed

**Comment by larsnaesbye** [comment]
So....the Travis build will work when pypuppetdb is out in v.1.0.0, right?

**Comment by bastelfreak** [comment]
Yes it should.  I will try to have a look in the next days for a pypuppetdb. Any help for an updated changelog there is appreciated.

**Comment by larsnaesbye** [comment]
https://github.com/voxpupuli/pypuppetdb/pull/150 <- there you go!

**Comment by bastelfreak** [comment]
Hi. I published the pypuppetdb release. I will now try to release puppetboard.

**Pull request merged**
