### PR TITLE
[Security] Implement bandit

### PR DESCRIPTION
**Pull request by roidelapluie**
Bandit (https://github.com/openstack/bandit) is a python
security linter.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by petems** [comment]
This seems simple, safe and a benefit for catching any AppSec issues. LGTM 👍

**Comment by mterzo** [comment]
Safe simple, shell script in necessary. Also is there a way to collect results?

**Comment by roidelapluie** [comment]
what do you mean collecting results? if we introduce security problems it will fail the build

**Comment by mterzo** [comment]
So completely binary pass/fail. No this is a deprecated warning. As such?

**Comment by roidelapluie** [comment]
Indeed. If we have false positive we can use control comments.

**Pull request merged**
