### PR TITLE
Fix dailychart in python3 + write a test for it

### PR DESCRIPTION
**Pull request by redref**
Everything in the title.

### CODE REVIEW

**Comment by mterzo** [comment]
I don't understand why have 2 modes when it never gets called the other way.

**Comment by redref** [comment]
Just in case, we wanted to iterate the other way. We may put this method into utils later.

**Comment by redref** [comment]
Let me know.

**Comment by redref** [comment]
This must be in the release IMO.

**Comment by mterzo** [comment]
@redref can you figure out why there are 6 commits on this?

**Comment by redref** [comment]
Much better !

**Pull request merged**
