### PR TITLE
Add support for containerized PuppetBoard

### PR DESCRIPTION
**Pull request by tux-o-matic**
The current Dockerfile in the project doesn't deliver PuppetBoard as a ready to use container.
Some changes to the code were also necessary in order to support specifying PuppetDB connection parameters to an immutable container image via ENV parameters set at runtime.
- The most important PuppetDB connection info will be first looks up in current ENV and fallback to configuration file.
- A new route was added to serve static resources directly via Gunicorn/Flask. This way it's not necessary to add a reverse proxy in front of the Puppet Board instance just to serve /static.

### CODE REVIEW

**Comment by corey-hammerton** [comment]
Have you verified that the `app.py` changes still work on a regular OS install?
Can you check the Travis CI errors?

**Comment by tux-o-matic** [comment]
@corey-hammerton no breaking change with this code for a regular installation using settings.py rather than ENV variables. Same goes for static, if the location is defined in Apache or Nginx (test), that's how the resources will be served.
CI is green after indention corrections.

**Comment by tux-o-matic** [comment]
A new release of PuppetBoard on PyPi will be required to use this container since it uses 'pip' internally.

**Comment by corey-hammerton** [comment]
With the new `settings.py` file in this PR it appears that it contains settings specific to your environment, most notably the `PUPPETDB_HOST` setting. Because of this I cannot accept this PR. 

My suggestion is to update `README.rst` with instructions of how users can configure their containers that fit their environments.

**Comment by tux-o-matic** [comment]
@corey-hammerton  I removed the local settings file and added steps to use the new Dockerfile in the README.

**Comment by mterzo** [comment]
What's the purpose of this change?  The Dockerfile now installs the latest released version of puppetboard, which will only be determined at build time,  when you already have a specific version checked out. 

Also, all the performance numbers I've seen is uwsgi > gunicorn. 

I use this existing docker container for my deployment. I set the settings.py env variable which points to a volume that has my settings and keys that are needed to establish a connection.

**Comment by tux-o-matic** [comment]
@mterzo this new container can do everything out of the box and can run anywhere once the image is built. The current one requires a build for every change in the settings and requires a reverse proxy to run in front of it.

As for performance, I kept this one pretty simple but for most usage I assume this gunicorn with sync worker will be enough. We could make Gunicorn use eventlet/gevent/gthread if you have scenarios with a lot of users, to which I would recommend adding a container with Nginx in front to add some caching.

**Comment by mterzo** [comment]
@tux-o-matic I have multiple web services on one host the only option is a proxy. 

I want to run puppetboard:0.2.0. When I build that container I better get 0.2.0. This will get whatever the latest in pypi.

**Comment by tux-o-matic** [comment]
@mterzo this new container doesn't stop you from using a reverse proxy in front of it. The choice is up to you but at least it can provide a working PuppetBoard without re-building for every host or serving static resources from a secondary service.

As for the version, VoxPupuli should publish a Docker image on the DockerHub along with every release.
So real world usage would be very simple from a usage point of view
```shell
docker run -e PUPPETBOARD_PUPPETDB_HOST=some.ip.or.name voxpupuli/puppetboard:0.2.1
```

**Comment by mterzo** [comment]
@tux-o-matic gunicorn 19.6.0, doesn't serve files under /static.  I ended up having to run supervisor and nginx to host the static files.  I don't see how the static js / css files will get served.

**Comment by tux-o-matic** [comment]
@mterzo if your container implementation resorts to using supervisord then something is really wrong.
My PR with a Flask route for static did work without the need for Nginx/Apache. So again maybe we should leave one PR for the ENV variables and one for a new Docker support.

**Comment by mterzo** [comment]
@tux-o-matic it was another project I was trying it on. I couldn't get gunicorn to serve files out of /static even though it had it in being routed correctly in flask.  I'm concerned that newer gunicorn disabled this and now your container will have the same problem since you get the latest at build.

**Comment by tux-o-matic** [comment]
As long as there is a Flask route serving content via send_from_directory(), it should work, regardless of the WSGI server in front.

**Comment by mterzo** [comment]
That's what I thought. But looks like significant changes in the last few releases of gunicorn.

**Comment by mterzo** [comment]
It's was flask and gunicorn hand off that I was having a problem with on another app. When using /static.  The static_folder needs to be set when it changes from the relative path static.  The app path /static is ignored running flask inside gunicorn.

**Comment by mterzo** [comment]
Closing in favor of #310. Thanks @tux-o-matic you did heavy lift.

**Pull request closed without merging**
