### PR TITLE
Make the page title in the html templates a variable in default_settings.py

### PR DESCRIPTION
**Pull request by tparkercbn**
Make the page title in the html templates a variable called PAGE_TITLE in default_settings.py

Admins with many sites running separate puppetservers with separate puppetbords may find it useful to be able to chagen the page title from Puppetboard to something more site specific.

### CODE REVIEW

**Comment by tparkercbn** [comment]
Hello.  I don't understand the check that has failed here.  What can I do to pass the checks and get this pull request accepted?

Thanks

Tom

**Comment by mterzo** [comment]
Code coverage went down. We added coveralls to CI to make sure all our code is tested.  You can't add code without covering that code in test.

Also this doesn't extend to docker_settings.py which allows the configuration to be passed in as an ENV setting to the container.

**Comment by tparkercbn** [comment]
Thanks

Let me look at adding that to the docker_settings.py and to the test cases.

Tom

**Comment by mterzo** [comment]
Just looked at the coveralls report, in all theory the % should have gone up and not down.

You may need to rebase and resubmit.  You could have been behind on the master causing your report to go down instead of up.

docker_settings.py already has a bunch of coverage and should be a quick add.

**Comment by tparkercbn** [comment]
There we go.  That looks better.

**Comment by wyardley** [comment]
So are we still waiting for tests on this?
Also, @tparkercbn can you squash the commits?

**Comment by tparkercbn** [comment]
Hi.  I'm not a programmer (anymore) and haven't had time to write the
tests (it will take me a while to get the syntax correct) but I do plan
to.  If there is someone out there who can whip them up quickly I
wouldn't complain :)

I haven't done a squash before but I can figure that out.

Tom

**Comment by wyardley** [comment]
@tparkercbn I think the comment above suggests an example test.

**Comment by mterzo** [comment]
Let's get that test in there.

**Comment by tparkercbn** [comment]
I have added the tests.  A huge thanks to mterzo.  Your code worked
flawlessly.

The commits are a mess now though and scattered through commits from
other people making squashing tricky.   Is there a way to clean them up?

Tom

**Comment by mterzo** [comment]
From your branch:

git pull —rebase upstream master
git push —force origin <branch_name>

Should clear it up.

**Pull request merged**
