### PR TITLE
Add PQL endpoint to Query form

### PR DESCRIPTION
**Pull request by raphink**
Requires https://github.com/voxpupuli/pypuppetdb/pull/97

### CODE REVIEW

**Comment by corey-hammerton** [comment]
@raphink voxpupuli/pypuppetdb#97 has been merged and released can you please update your requirements.txt file in this PR with the new version?

**Comment by raphink** [comment]
You mean 0.4.0?

**Comment by raphink** [comment]
Ah no, 0.3.1

**Comment by raphink** [comment]
Done.

**Pull request merged**
