### PR TITLE
Default settings use environment variables

### PR DESCRIPTION
**Pull request by mterzo**
Update default_settings.py to behave as it exists today with it's settings, but allow for configuration to be overwritten using environment.  This allows for simpler docker deployments.

### CODE REVIEW

**Comment by mterzo** [comment]
I'm running into weird issue on this.  It works great when I use these new settings and point it to the remote server.  The idea is to run the puppetboard container on the puppetdb host.  When I do I get a weird IOError 13 Permission Denied.  I run in the same container with the same settings using the dev.py it works perfectly.  It look to be something with running under WSGI.  Any thoughts?

**Comment by tux-o-matic** [comment]
Couldn't we get #288 merged?
And if users may need to set extra parameters via environment, we could build on top of it.

**Comment by mterzo** [comment]
TODO: I need to squash my commits.

I completely forgot about #288.

Yeah, similar concept.  If the Dockerfile was a separate repo, I could see using pip to install puppetboard.  Since the the docker file is with the code, install the checked out code into the app location.  I want to make sure we "pin" the version of gunicorn as well. 

I reordering the layering of your docker file as well so that the "common" areas a higher.

Maybe the version of gunicorn is different if found it needs to be: --access-logfile=/dev/stdout , the PR had --access-log=/dev/stdout

I don't understand why you changed the static content.  Everything worked as expected.

**Comment by tux-o-matic** [comment]
@mterzo  Why duplicate so much from #288? If there had to be two PR, I'd rather have yours merged first to handle the ENV variable and then #288 for the Docker part.

Indeed Gunicorn log parameter changed between version. And yes the Docker Hub image should not just be :latest but distributed per puppetboard/gunicorn version.

I added a static route in Flask since the other routes in the app weren't meant to serve static files and expect Nginx/Apache to handle that route. In a container setup that's not the most user friendly approach.

**Comment by mterzo** [comment]
I looked at cherry picking but you had several different commits. I didn't want to pull them and then squash.

Personally, I'm strict on pinning the versions of modules.  Not providing the version of gunicorn or puppetboard it's difficult to know what was packaged with the container.

With some integration with docker hub and triggers we can easily use tagging and branching to build containerized versions of of puppetboard on every commit to master without having to use pip to install puppetboard.

**Comment by tux-o-matic** [comment]
GIT master always has the latest code, that's a safe assumption.
Option A:
And every time a new release is tagged on GIT then published on PyPI, the maintainer published a new image on DockerHub.
Option B:
The tagged Dockerfile pulls from GIT a certain git tag of PuppetBoard, but still uses pip for Gunicorn.

@mterzo: Do you know any mechanism to have either approaches done automatically?

**Comment by mterzo** [comment]
I use B on my repos. Having A you get a slew of packages.   We need the vox account linked on docker hub.

**Comment by mterzo** [comment]
@tux-o-matic I verified, It has everything to do with where the static_folder is being served.  when gunicorn is front ending flask.  flask doesn't use the app.route('/static') it uses the defines arguments passed in for static_folder and static_url.  static_url is default of '/static'.  if you want to place static content outside the app module directory you have to specify the static_folder=/path_to_content

I'm pretty happy with the way this is working.

```
docker run -it -v /my_ssl_certs:/certs \
  -e PUPPETDB_SSL_VERIFY=/certs/ca.pem -e PUPPETDB_KEY=/certs/private.pem \
  -e PUPPETDB_CERT=/certs/public.pem -e PUPPETDB_HOST=my_cool_host \
  -e PUPPETDB_PORT=8081 -p 9080:80 \
  -e INVENTORY_FACTS='Hostname,fqdn, IP Address,ipaddress' \
  -e GRAPH_FACTS="my_custom_fact" -e PUPPETBOARD_PORT=80 \
  -e "ENABLE_CATALOG=true"  puppetboard
```

**Comment by mterzo** [comment]
@tux-o-matic I've been running a container off this pull request now with only gunicorn. Works great!

**Comment by mterzo** [comment]
@tux-o-matic You want to take a look at this PR.  I think this solves what you were doing with #288.

**Comment by mterzo** [comment]
@tux-o-matic works like a charm.

**Comment by juniorsysadmin** [comment]
@mterzo @tux-o-matic Ready for merge?

**Comment by mterzo** [comment]
Yep, was waiting on the hub.docker changes for #312

**Pull request merged**
