### PR TITLE
Add wsgi.py and Dockerfile

### PR DESCRIPTION
**Pull request by raphink**
This PR adds support for easily developing and deploying Puppetboard with Docker.

### CODE REVIEW

**Comment by corey-hammerton** [comment]
I apologize for the late reply. Have you tested this new Docker file? I currently don't have a available resource for test a docker image.

**Comment by raphink** [comment]
We use puppetboard with docker in production, so yes, this is tested.

**Comment by corey-hammerton** [comment]
Thanks @raphink for the clarification. Since this implies that a new package system must be maintained I've added this PR to the 0.2.0 milestone, also because this involves changing an existing value in ``default_settings.py``

**Comment by corey-hammerton** [comment]
Is there a way to provide an external configuration option for their docker containers, for example provide a ``settings.py`` file to be accessible via the ``env['PUPPETBOARD_SETTINGS']``?

**Comment by corey-hammerton** [comment]
@raphink I will merge this into the tree. However there will not be an officially maintained Docker image. I have found nothing on Docker Hub that suggests the voxpupuli community maintains any images.

**Comment by raphink** [comment]
@corey-hammerton there's no images yet indeed. @puppetlabs has started maintaining images though, and I think it would make sense to have an account for @voxpupuli too.

**Comment by corey-hammerton** [comment]
One last thing. I'm not comfortable with changing the `PUPPETDB_HOST` value in `default_settings.py` because it might cause unnecessary disruption for users upgrading to new versions.

**Comment by raphink** [comment]
I could add a script to edit that value when building the image, like we do in ours. `localhost` makes no sense in a container.

**Comment by corey-hammerton** [comment]
Or, probably preferably, we could maintain a separate branch that will contain docker specific files/settings. Then use that for building and maintaining the images.

**Comment by bastelfreak** [comment]
I think a deploy script that does the changes via travis or $awesomething is the better approach compared to a seperate branch. Two branches will result in two sources of truth - which is bad.

**Comment by raphink** [comment]
Yes, two branches will cause issues.

**Comment by corey-hammerton** [comment]
I will merge this, however, until we figure out how we can configure puppetboard settings in the image there will not be an officially supported Docker image. 

I'll also add to the README that this is planned.

**Pull request merged**
