### PR TITLE
update c3 to 4.22

### PR DESCRIPTION
**Pull request by larsnaesbye**
Updates c3 to 4.22 to fix a few gauge-related bugs. Didn't want to go further yet because of d3 dependencies.

### CODE REVIEW

**Comment by othalla** [comment]
Hi, think we can merge this

**Comment by larsnaesbye** [comment]
I don't know why it fails with Python 3.5 in Travis.....

**Comment by larsnaesbye** [comment]
@baurmatt : This should be a straightforward merge I guess?

**Comment by baurmatt** [comment]
Hey @larsnaesbye, I guess it is. But I'm not really familiar with CSS/JS and don't run a instance of Puppetdashboad myself on which I could test your change :( Sorry!

**Comment by bastelfreak** [comment]
Hi @larsnaesbye, can you please rebase after https://github.com/voxpupuli/puppetboard/pull/489 got merged?

**Comment by baurmatt** [comment]
Hey @larsnaesbye, #489 got merged. Could you please rebase this branch?

**Comment by larsnaesbye** [comment]
Having trouble rebasing w/remote branch, following [this link.](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) Wouldn't it be easier to just close it and make another pull request?

**Comment by bastelfreak** [comment]
The rebase should be as easy as this:

```
git clone git@github.com:larsnaesbye/puppetboard.git
cd puppetboard
git checkout
git remote add upstream git@github.com:voxpupuli/puppetboard.git
git fetch upstream
git rebase upstream/master
git push -f origin/master
```

If you have any issues you can reach us in our IRC channel #voxpupuli on freenode or at https://slack.puppet.com

**Comment by larsnaesbye** [comment]
Done and passed :-)

**Comment by bastelfreak** [comment]
Thanks!

**Pull request merged**
