### PR TITLE
Make node row in inventory link to node page

### PR DESCRIPTION
**Pull request by tux-o-matic**
To improve UX, made each element in an inventory row clickable to get to the node page.

### CODE REVIEW

**Comment by corey-hammerton** [comment]
I've opened #275 which will result in a huge refactoring of the code managing the Inventory page. I will also consider making each table item link to their node page.

**Comment by tux-o-matic** [comment]
@corey-hammerton  do you expect to change structure of the data passed to the template? If not, this PR could be merged now.

**Comment by corey-hammerton** [comment]
I do expect the data structure for the template to change. Thank you for your submission though.

**Comment by corey-hammerton** [comment]
Closing in favour of #289

**Pull request closed without merging**
