### PR TITLE
catch a division by zero in radiator while environment has no nodes

### PR DESCRIPTION
**Pull request by rmdir**
In radiator, when an environment as no nodes, num_nodes is null. This patch catch the divisions by zero and set the results to 0 in this case

### CODE REVIEW

**Comment by mterzo** [comment]
I get your problem.  If nodes are 0, which is causing the division by zero error. shouldn't the other values be 0 as well?

so,  if number of nodes == 0 then set nodes to 1, and it all should show up as 0% making the code a bit simpiler.

**Comment by mterzo** [comment]
So I did a quick test, my assumption was correct, but the problem is that number of nodes reported is 1, instead of 0.

The only way I was able to reproduce this was to create a node in an environment, then delete that 1 node from that environment.  Is that the scenario you have?

**Comment by mterzo** [comment]
I would like to pull this in, can you squash this into 1 commit?

**Comment by corey-hammerton** [comment]
@mterzo Github has a "Squash and merge" option, along with "Create a merge commit" and "Rebase and merge"

**Comment by mterzo** [comment]
@corey-hammerton thank you, i never noticed.

**Comment by rmdir** [comment]
@mterzo Thanks for the commit.

**Pull request merged**
