### PR TITLE
Update README, addressing #421 and #412

### PR DESCRIPTION
**Pull request by larsnaesbye**
Made two changes to the README, removing old mentioning of stability issues no longer relevant, and adding note about PuppetDB compatibility.

### CODE REVIEW

**Comment by mterzo** [comment]
So it also works on puppetdb 4. 

You running this on python3?

**Comment by larsnaesbye** [comment]
No, Python 2.7.

**Comment by mterzo** [comment]
I’ll throw it into a python3 container tonight and see if blows up. And we can update the readme all at once.

**Comment by mterzo** [comment]
Works in Python 3.6 as well.  Can you update the readme and i'll merge this.

**Pull request merged**
