### PR TITLE
puppetboard/app.py: Enhancing queries for Node and Report states

### LINKED ISSUE #264: Query Clauses for Node/Report States
Update the Nodes Tab source-code to add query filters based on the `status` argument value

* If `failed`, `changed` or `unchanged` check the `latest_report_status` query field
* If `unreported` check  the `report_timestamp` query field for Null or less-than `UNREPORTED_TIME` hours ago
* `noop` will have to remain its old functionality since this query field was added in PuppetDB 4.1 and we will not break 4.0 functionality

Add a `status` query string argument to the Reports tab to add PuppetDB query clauses based on its value

* If `failed`, `changed` or `unchanged` check the `status` query field
* If `noop` check the `noop` field for true

### PR DESCRIPTION
**Pull request by corey-hammerton**
This resolves #264

On the Nodes and Reports tabs when the user adds a status query string
argument additional query clauses are generated based on its value.
Can be one of failed, changed, unchanged, noop or unreported (for Nodes
only)

No query clause is generated for noop on the Nodes tab. The query field
latest_report_noop was added in PuppetDB 4.1 and we do not want to break
compatability between minor or bug-fix versions.

### CODE REVIEW

**Comment by mterzo** [comment]
Cool. Probably need to add a new snapshot.

**Comment by mterzo** [comment]
Limit doesn't seem to work. Always shows 10 results.

**Comment by corey-hammerton** [comment]
@mterzo Are you still experiencing this problem? Can you include your puppetboard and puppetdb logs to help troubleshoot?

**Comment by redref** [comment]
@corey-hammerton 

pypuppetdb "nodes" already provide specific work on "status" field. Don't you think these modifications (filter / count behavior) should be done on pypuppetdb (api/QueryBuilder) side ? Providing a consistent "status" query part.

**Comment by corey-hammerton** [comment]
Status query syntax is very dependant on the Endpoint we are querying. The Reports endpoint provides a `status` and `noop` field as opposed to the Nodes endpoint which provides a `latest_report_status` and `latest_report_noop` field (the latter added in PuppetDB 4.1).

**Comment by redref** [comment]
Reading pypuppetdb, I got your point. Query is stringified before getting to an endpoint routine, with no further modifications possible.

Still, it's kinda weird to get consolidated "status" in nodes endpoint (on pypuppetdb side) and be forced to explicitly filter/count on "latest_report_status" (on puppetboard side). Border between library and application is not fully established.

IMO, it will be clearer to disable "with_status" flag on puppetboard side (doing it explicitly just like filters).

**Comment by mterzo** [comment]
I haven't pulled in a while to check.

**Comment by mterzo** [comment]
Yeah, still broken. reports vs reports_node.

Here's a quick diff for reports pagination on the node list.

```
diff --git a/puppetboard/app.py b/puppetboard/app.py
index 4bbbac4..13a9b49 100644
--- a/puppetboard/app.py
+++ b/puppetboard/app.py
@@ -571,11 +571,18 @@ def reports_node(env, node_name, page):
     query.add(EqualsOperator("certname", node_name))
     total_query.add_query(query)
 
+    limit = request.args.get('limit', app.config['REPORTS_COUNT'])
+
+    try:
+        paging_args = {'limit': int(limit)}
+        paging_args['offset'] = int((page - 1) * paging_args['limit'])
+    except ValueError:
+        paging_args = {}
+
     reports = get_or_abort(puppetdb.reports,
                            query=query,
-                           limit=app.config['REPORTS_COUNT'],
-                           offset=(page - 1) * app.config['REPORTS_COUNT'],
-                           order_by=DEFAULT_ORDER_BY)
+                           order_by=DEFAULT_ORDER_BY,
+                           **paging_args)
     total = get_or_abort(puppetdb._query,
                          'reports',
                          query=total_query)
@@ -615,7 +622,7 @@ def reports_node(env, node_name, page):
         reports=reports,
         reports_count=app.config['REPORTS_COUNT'],
         report_event_counts=report_event_counts,
-        pagination=Pagination(page, app.config['REPORTS_COUNT'], total),
+        pagination=Pagination(page, paging_args.get('limit', total), total),
         envs=envs,
         current_env=env)
```

**Pull request merged**
