### PR TITLE
Make the query shareable using URL

### PR DESCRIPTION
**Pull request by GermanG**
This is a PR with the code in #655

### CODE REVIEW

**Comment by gdubicki** [comment]
Thanks for the PR!

Can you please share some screenshots for a quick glance how it looks, @GermanG ?

**Comment by gdubicki** [comment]
LGTM! 👍 

I don't understand why you wrote [here](https://github.com/voxpupuli/puppetboard/issues/655#issuecomment-1014562475) that you don't like the UX though - what could we do better in your opinion?

**Comment by GermanG** [comment]
I'm not completely happy with the UX because I'd like to have a "copy query" or "share" button to hit (so I won't need to select the URL myself) and the query is not submitted automagically when you visit the shared link.

**Comment by gdubicki** [comment]
True, it could be improved. But the proposed changes won't break the compatibility with the existing solution and they can be done in a new PR so let's get this merged and released already. Thank you for your contribution, @GermanG!

**Pull request merged**
