### PR TITLE
Failures view

### PR DESCRIPTION
**Pull request by gdubicki**
This is a draft of a new view that would help finding the most common errors in puppet runs to resolve them faster.

To do that it would list all the nodes with errors in their last puppet run and for each of them show the first meaningful error in it.

### CODE REVIEW

**Comment by gdubicki** [comment]
It's totally unfinished, including the UI & UX, but would very roughly look like this:

Screenshot_2022-02-18_at_08_44_38

**Comment by tparkercbn** [comment]
This looks like an amazing addition!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gdubicki** [comment]
For a long time now I was thinking that Puppet's error messages can and should be improved. They contain a lot of redundancy, are not well formatted for readability. Therefore I added a feature for it here. I would like to optionally make it available in the report view too, while doing #641.

Example "raw" error:

Screenshot_2022-02-27_at_20_46_24

...and its "friendly" version:

Screenshot 2022-02-27 at 20 46 59

Opinions?

**Comment by gdubicki** [comment]
Current view of the failures page:
Screenshot_2022-02-27_at_20_54_43

**Pull request merged**
