### PR TITLE
Fix problem loading daily chart on node page

### PR DESCRIPTION
**Pull request by kirkins**
Fix for #424 by referencing base site url plus daily report location.

### CODE REVIEW

**Comment by kirkins** [comment]
**Daily node page with change:**

untitled

**Chart on front-page still working:**

untitled

**Comment by mterzo** [comment]
Can we trust that DOM value for all browsers?

**Comment by kirkins** [comment]
@mterzo good call, I think there are some older browsers that will have trouble with `window.location.origin` I'm going to add a polyfill to handle that.

**Comment by kirkins** [comment]
Updated for IE, with solution from here https://stackoverflow.com/a/25495161/773263

**Comment by mterzo** [comment]
I was gonna keep this simple and move dailychart to the templates and generate the base url.

**Comment by bastelfreak** [comment]
@mterzo can you please take a look at this again?

**Pull request merged**
