### PR TITLE
Add download as CSV/XLSX to Query results + update static assets

### PR DESCRIPTION
**Pull request by gdubicki**
Additionally update jQuery and other JS & CSS related to DataTables.

### CODE REVIEW

**Comment by gdubicki** [comment]
This is how the buttons and query results in non-JSON mode will look:

Screenshot 2022-01-15 at 15 31 32

**Comment by gdubicki** [comment]
This partially implements #428. Extending it to cover all the tables can be added in another PR and I would be happy if someone else would like to do it. :)

**Review by bastelfreak — CHANGES_REQUESTED** [review]
updating the static files doe not relate to the new feature? please put that into a dedicated PR. Do you have any semiautomatic way for updating the files? If so, please document that.

**Comment by gdubicki** [comment]
> updating the static files doe not relate to the new feature? please put that into a dedicated PR. Do you have any semiautomatic way for updating the files? If so, please document that.

That request makes a lot of sense. However as I was adding a new feature that is using a new library I have added it in the latest stable version. And to avoid compatibility issues I updated the related libraries too.

Theoretically I could downgrade Datatables Buttons to a version compatible with the version of Datatables that we had before the upgrade but I don't even know which that is - they are versioned separately and [the website doesn't allow choosing older versions on their download page](https://datatables.net/download/index).

Because of that and because we didn't upgrade any _major_ version here, I think that we can keep this change in this PR.

**Review by bastelfreak — APPROVED** [review]

**Review by sebastianrakel — APPROVED** [review]

**Pull request merged**
